[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
position = "17% 6%"
size = "65% 60%"
offset = "200%"

[scratchpads.onps]
animation = "fromRight"
command = "kitty --class kitty-onps onps"
class = "kitty-onps"
size = "10% 20%"
offset = "200%"

[scratchpads.music]
animation = "fromBottom"
command = "kitty --class kitty-pulsemixer -e pulsemixer"
class = "kitty-pulsemixer"
size = "50% 20%"
offset = "200%"

[scratchpads.spotify]
animation = "fromTop"
command = "spotify"
class = "spotify"
size = "45% 55%"
offset = "200%"

[scratchpads.taskbar]
animation = "fromLeft"
command = "kitty --class kitty-taskbar -e btop"
class = "kitty-taskbar"
size = "30% 80%"
offset = "200%"

[scratchpads.network]
animation = "fromRight"
command = "kitty --class kitty-network -e ~/.config/hypr/nmtui.sh"
class = "kitty-network"
size = "20% 60%"
offset = "200%"

[scratchpads.bt]
animation = "fromRight"
command = "kitty --class kitty-bt -e bluetui"
class = "kitty-bt"
size = "20% 60%"
offset = "200%"
